version: '3.8'

services:
  ingress:
    networks:
      - default
    build:
      context: .
    image: lovelove-ingress

  server:
    build:
      context: ./server
    image: lovelove-server

networks:
  ingress_link:
    external: true
